name: DataSHIELD Docker image build
run-name: ${{ github.actor }} is building Docker image
on: [push]
jobs:
  build-datashield-base-image:
    runs-on: ubuntu-latest
    steps:
      using: 'docker'
      image: 'Dockerfile'
