name: DataSHIELD Docker image build
run-name: ${{ github.actor }} is building Docker image
on: [push]
jobs:
  build-datashield-base-image:
    runs-on: ubuntu-latest
    name: Build Docker Images
    steps:
      - name: Build Base Client Docker Image
      - run: docker build -t datashield/githubactions-dsclient-base:latest --file dsClient_Dockerfile .
      - run: echo ${{ dockerhub.password }} | docker login -u ${{ dockerhub.user }} --password-stdin
      - run: docker push datashield/githubsactions-dsclient-base:latest
