name: DataSHIELD Docker image build
run-name: ${{ github.actor }} is building Docker image
on: [push]
jobs:
  build-datashield-base-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-push-action@3
      - uses: docker/setup-push-action@3
      - run: docker build -t datashield/githubactions-dsclient-base:latest --file dsClient_Dockerfile .
      - run: docker push datashield/githubsactions-dsclient-base:latest
